eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  profiles:
   active: uat
  application:
    name: order
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
        block-when-exhausted: true
        database: 1
        host: 192.168.242.128
        jedis:
          pool:
            max-active: 1024
            max-idle: 200
            max-wait: 10000
            min-idle: 0
        password: '123456'
        port: 6379
        timeout: 10000
  activemq:
    broker-url: tcp://127.0.0.1:61616
    password: jackson123
    username: jackson
  rabbitmq:
     host: 192.168.221.254
     port: 5677
     username: uat
     password: uat
     virtual-host: /uat
     exchange: transaction
     publisher-confirms: true
     publisher-returns: true
     listener:
       simple:
         acknowledge-mode: manual 
         retry:
           enabled: true
           max-attempts: 2
           initial-interval: 1000
feign:
  hystrix:
     enabled: false
dawdler:
  transaction:
    mqserver: rabbitmq
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.pttl.service.order.entity